using System;
using UAssetAPI.UnrealTypes;

namespace UAssetAPI.CustomVersions
{
    /// <summary>
    /// Represents the engine version at the time that a custom version was implemented.
    /// </summary>
    [AttributeUsage(AttributeTargets.Field)]
    public class IntroducedAttribute : Attribute
    {
        public EngineVersion IntroducedVersion;

        public IntroducedAttribute(EngineVersion introducedVersion)
        {
            IntroducedVersion = introducedVersion;
        }
    }

    /// <summary>
    /// Custom serialization version for changes made in the //Fortnite/Main stream.
    /// </summary>
    public enum FFortniteMainBranchObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded = 0,

        /// <summary>World composition tile offset changed from 2d to 3d</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        WorldCompositionTile3DOffset,

        /// <summary>Minor material serialization optimization</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        MaterialInstanceSerializeOptimization_ShaderFName,

        /// <summary>Refactored cull distances to account for HLOD, explicit override and globals in priority</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        CullDistanceRefactor_RemovedDefaultDistance,
        [Introduced(EngineVersion.VER_UE4_20)]
        CullDistanceRefactor_NeverCullHLODsByDefault,
        [Introduced(EngineVersion.VER_UE4_20)]
        CullDistanceRefactor_NeverCullALODActorsByDefault,

        /// <summary>Support to remove morphtarget generated by bRemapMorphtarget</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        SaveGeneratedMorphTargetByEngine,

        /// <summary>Convert reduction setting options</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        ConvertReductionSettingOptions,

        /// <summary>Serialize the type of blending used for landscape layer weight static params</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        StaticParameterTerrainLayerWeightBlendType,

        /// <summary>Fix up None Named animation curve names,</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        FixUpNoneNameAnimationCurves,

        /// <summary>Ensure ActiveBoneIndices to have parents even not skinned for old assets</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        EnsureActiveBoneIndicesToContainParents,

        /// <summary>Serialize the instanced static mesh render data, to avoid building it at runtime</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        SerializeInstancedStaticMeshRenderData,

        /// <summary>Cache material quality node usage</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        CachedMaterialQualityNodeUsage,

        /// <summary>Font outlines no longer apply to drop shadows for new objects but we maintain the opposite way for backwards compat</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        FontOutlineDropShadowFixup,

        /// <summary>New skeletal mesh import workflow (Geometry only or animation only re-import )</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        NewSkeletalMeshImporterWorkflow,

        /// <summary>Migrate data from previous data structure to new one to support materials per LOD on the Landscape</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        NewLandscapeMaterialPerLOD,

        /// <summary>New Pose Asset data type</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        RemoveUnnecessaryTracksFromPose,

        /// <summary>Migrate Foliage TLazyObjectPtr to TSoftObjectPtr</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        FoliageLazyObjPtrToSoftObjPtr,

        /// <summary>TimelineTemplates store their derived names instead of dynamically generating. This code tied to this version was reverted and redone at a later date</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        REVERTED_StoreTimelineNamesInTemplate,

        /// <summary>Added BakePoseOverride for LOD setting</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        AddBakePoseOverrideForSkeletalMeshReductionSetting,

        /// <summary>TimelineTemplates store their derived names instead of dynamically generating</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        StoreTimelineNamesInTemplate,

        /// <summary>New Pose Asset data type</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        WidgetStopDuplicatingAnimations,

        /// <summary>Allow reducing of the base LOD, we need to store some imported model data so we can reduce again from the same data.</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        AllowSkeletalMeshToReduceTheBaseLOD,

        /// <summary>Curve Table size reduction</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        ShrinkCurveTableSize,

        /// <summary>Widgets upgraded with WidgetStopDuplicatingAnimations, may not correctly default-to-self for the widget parameter.</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        WidgetAnimationDefaultToSelfFail,

        /// <summary>HUDWidgets now require an element tag</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        FortHUDElementNowRequiresTag,

        /// <summary>Animation saved as bulk data when cooked</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        FortMappedCookedAnimation,

        /// <summary>Support Virtual Bone in Retarget Manager</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        SupportVirtualBoneInRetargeting,

        /// <summary>Fixup bad defaults in water metadata</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        FixUpWaterMetadata,

        /// <summary>Move the location of water metadata</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        MoveWaterMetadataToActor,

        /// <summary>Replaced lake collision component</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        ReplaceLakeCollision,

        /// <summary>Anim layer node names are now conformed by Guid</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        AnimLayerGuidConformation,

        /// <summary>Ocean collision component has become dynamic</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        MakeOceanCollisionTransient,

        /// <summary>FFieldPath will serialize the owner struct reference and only a short path to its property</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        FFieldPathOwnerSerialization,

        /// <summary>Simplified WaterBody post process material handling</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        FixUpUnderwaterPostProcessMaterial,

        /// <summary>A single water exclusion volume can now exclude N water bodies</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        SupportMultipleWaterBodiesPerExclusionVolume,

        /// <summary>Serialize rigvm operators one by one instead of the full byte code array to ensure determinism</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        RigVMByteCodeDeterminism,

        /// <summary>Serialize the physical materials generated by the render material</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        LandscapePhysicalMaterialRenderData,

        /// <summary>RuntimeVirtualTextureVolume fix transforms</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        FixupRuntimeVirtualTextureVolume,

        /// <summary>Retrieve water body collision components that were lost in cooked builds</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        FixUpRiverCollisionComponents,

        /// <summary>Fix duplicate spline mesh components on rivers</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        FixDuplicateRiverSplineMeshCollisionComponents,

        /// <summary>Indicates level has stable actor guids</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        ContainsStableActorGUIDs,

        /// <summary>Levelset Serialization support for BodySetup.</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        LevelsetSerializationSupportForBodySetup,

        /// <summary>Moving Chaos solver properties to allow them to exist in the project physics settings</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        ChaosSolverPropertiesMoved,

        /// <summary>Moving some UFortGameFeatureData properties and behaviors into the UGameFeatureAction pattern</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        GameFeatureData_MovedComponentListAndCheats,

        /// <summary>Add centrifugal forces for cloth</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        ChaosClothAddfictitiousforces,

        /// <summary>Chaos Convex StructureData supports different index sizes based on num verts/planes. Chaos FConvex uses array of FVec3s for vertices instead of particles (Merged from //UE4/Main)</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        ChaosConvexVariableStructureDataAndVerticesArray,

        /// <summary>Remove the WaterVelocityHeightTexture dependency on MPC_Landscape and LandscapeWaterIndo</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        RemoveLandscapeWaterInfo,

        // CHANGES BEYOND HERE ARE UE5 ONLY //

        /// <summary>Added the weighted value property type to store the cloths weight maps' low/high ranges</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        ChaosClothAddWeightedValue,

        /// <summary>Added the Long Range Attachment stiffness weight map</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        ChaosClothAddTetherStiffnessWeightMap,

        /// <summary>Fix corrupted LOD transition maps</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        ChaosClothFixLODTransitionMaps,

        /// <summary>Enable a few more weight maps to better art direct the cloth simulation</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        ChaosClothAddTetherScaleAndDragLiftWeightMaps,

        /// <summary>Enable material (edge, bending, and area stiffness) weight maps</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        ChaosClothAddMaterialWeightMaps,

        /// <summary>Added bShowCurve for movie scene float channel serialization</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        SerializeFloatChannelShowCurve,

        /// <summary>Minimize slack waste by using a single array for grass data</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        LandscapeGrassSingleArray,

        /// <summary>Add loop counters to sequencer's compiled sub-sequence data</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        AddedSubSequenceEntryWarpCounter,

        /// <summary>Water plugin is now component-based rather than actor based</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        WaterBodyComponentRefactor,

        /// <summary>Cooked BPGC storing editor-only asset tags</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        BPGCCookedEditorTags,

        /// <summary>Terrain layer weights are no longer considered material parameters</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        TerrainLayerWeightsAreNotParameters,

        /// <summary>
        /// Anim Dynamics Node Gravity Override vector is now defined in world space, not simulation space. 
        /// Legacy behavior can be maintained with a flag, which is set false by default for new nodes, 
        /// true for nodes predating this change.
        /// </summary>
        GravityOverrideDefinedInWorldSpace,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    };

    /// <summary>
    /// Custom serialization version for changes made in Dev-Framework stream.
    /// </summary>
    public enum FFrameworkObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded = 0,

        /// <summary>BodySetup's default instance collision profile is used by default when creating a new instance.</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        UseBodySetupCollisionProfile,

        /// <summary>Regenerate subgraph arrays correctly in animation blueprints to remove duplicates and add missing graphs that appear read only when edited</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        AnimBlueprintSubgraphFix,

        /// <summary>Static and skeletal mesh sockets now use the specified scale</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        MeshSocketScaleUtilization,

        /// <summary>Attachment rules are now explicit in how they affect location, rotation and scale</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        ExplicitAttachmentRules,

        /// <summary>Moved compressed anim data from uasset to the DDC</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        MoveCompressedAnimDataToTheDDC,

        /// <summary>Some graph pins created using legacy code seem to have lost the RF_Transactional flag, which causes issues with undo. Restore the flag at this version</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        FixNonTransactionalPins,

        /// <summary>Create new struct for SmartName, and use that for CurveName</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        SmartNameRefactor,

        /// <summary>Add Reference Skeleton to Rig</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        AddSourceReferenceSkeletonToRig,

        /// <summary>Refactor ConstraintInstance so that we have an easy way to swap behavior paramters</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        ConstraintInstanceBehaviorParameters,

        /// <summary>Pose Asset support mask per bone</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        PoseAssetSupportPerBoneMask,

        /// <summary>Physics Assets now use SkeletalBodySetup instead of BodySetup</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        PhysAssetUseSkeletalBodySetup,

        /// <summary>Remove SoundWave CompressionName</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        RemoveSoundWaveCompressionName,

        /// <summary>Switched render data for clothing over to unreal data, reskinned to the simulation mesh</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        AddInternalClothingGraphicalSkinning,

        /// <summary>Wheel force offset is now applied at the wheel instead of vehicle COM</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        WheelOffsetIsFromWheel,

        /// <summary>Move curve metadata to be saved in skeleton. Individual asset still saves some flag - i.e. disabled curve and editable or not, but major flag - i.e. material types - moves to skeleton and handle in one place</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        MoveCurveTypesToSkeleton,

        /// <summary>Cache destructible overlaps on save</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        CacheDestructibleOverlaps,

        /// <summary>Added serialization of materials applied to geometry cache objects</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        GeometryCacheMissingMaterials,

        /// <summary>Switch static and skeletal meshes to calculate LODs based on resolution-independent screen size</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        LODsUseResolutionIndependentScreenSize,

        /// <summary>Blend space post load verification</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        BlendSpacePostLoadSnapToGrid,

        /// <summary>Addition of rate scales to blend space samples</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        SupportBlendSpaceRateScale,

        /// <summary>LOD hysteresis also needs conversion from the LODsUseResolutionIndependentScreenSize version</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        LODHysteresisUseResolutionIndependentScreenSize,

        /// <summary>AudioComponent override subtitle priority default change</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        ChangeAudioComponentOverrideSubtitlePriorityDefault,

        /// <summary>Serialize hard references to sound files when possible</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        HardSoundReferences,

        /// <summary>Enforce const correctness in Animation Blueprint function graphs</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        EnforceConstInAnimBlueprintFunctionGraphs,

        /// <summary>Upgrade the InputKeySelector to use a text style</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        InputKeySelectorTextStyle,

        /// <summary>Represent a pins container type as an enum not 3 independent booleans</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        EdGraphPinContainerType,

        /// <summary>Switch asset pins to store as string instead of hard object reference</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        ChangeAssetPinsToString,

        /// <summary>Fix Local Variables so that the properties are correctly flagged as blueprint visible</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        LocalVariablesBlueprintVisible,

        /// <summary>Stopped serializing UField_Next so that UFunctions could be serialized in dependently of a UClass in order to allow us to do all UFunction loading in a single pass (after classes and CDOs are created)</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        RemoveUField_Next,

        /// <summary>Fix User Defined structs so that all members are correct flagged blueprint visible</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        UserDefinedStructsBlueprintVisible,

        /// <summary>FMaterialInput and FEdGraphPin store their name as FName instead of FString</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        PinsStoreFName,

        /// <summary>User defined structs store their default instance, which is used for initializing instances</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        UserDefinedStructsStoreDefaultInstance,

        /// <summary>Function terminator nodes serialize an FMemberReference rather than a name/class pair</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        FunctionTerminatorNodesUseMemberReference,

        /// <summary>Custom event and non-native interface event implementations add 'const' to reference parameters</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        EditableEventsUseConstRefParameters,

        /// <summary>No longer serialize the legacy flag that indicates this state, as it is now implied since we don't serialize the skeleton CDO</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        BlueprintGeneratedClassIsAlwaysAuthoritative,

        /// <summary>Enforce visibility of blueprint functions - e.g. raise an error if calling a private function from another blueprint:</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        EnforceBlueprintFunctionVisibility,

        /// <summary>ActorComponents now store their serialization index</summary>
        [Introduced(EngineVersion.VER_UE4_25)]
        StoringUCSSerializationIndex,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    };

    /// <summary>
    /// Custom serialization version for changes made in Dev-Core stream.
    /// </summary>
    public enum FCoreObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded = 0,

        [Introduced(EngineVersion.VER_UE4_12)]
        MaterialInputNativeSerialize,

        [Introduced(EngineVersion.VER_UE4_15)]
        EnumProperties,

        [Introduced(EngineVersion.VER_UE4_22)]
        SkeletalMaterialEditorDataStripping,

        [Introduced(EngineVersion.VER_UE4_25)]
        FProperties,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    };

    /// <summary>
    /// Custom serialization version for changes made in Dev-Editor stream.
    /// </summary>
    public enum FEditorObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded = 0,

        /// <summary>Localizable text gathered and stored in packages is now flagged with a localizable text gathering process version</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        GatheredTextProcessVersionFlagging,

        /// <summary>Fixed several issues with the gathered text cache stored in package headers</summary>
        [Introduced(EngineVersion.VER_UE4_12)]
        GatheredTextPackageCacheFixesV1,

        /// <summary>Added support for "root" meta-data (meta-data not associated with a particular object in a package)</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        RootMetaDataSupport,

        /// <summary>Fixed issues with how Blueprint bytecode was cached</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        GatheredTextPackageCacheFixesV2,

        /// <summary>Updated FFormatArgumentData to allow variant data to be marshaled from a BP into C++</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        TextFormatArgumentDataIsVariant,

        /// <summary>Changes to SplineComponent</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        SplineComponentCurvesInStruct,

        /// <summary>Updated ComboBox to support toggling the menu open, better controller support</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        ComboBoxControllerSupportUpdate,

        /// <summary>Refactor mesh editor materials</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        RefactorMeshEditorMaterials,

        /// <summary>Added UFontFace assets</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        AddedFontFaceAssets,

        /// <summary>Add UPROPERTY for TMap of Mesh section, so the serialize will be done normally (and export to text will work correctly)</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        UPropertryForMeshSection,

        /// <summary>Update the schema of all widget blueprints to use the WidgetGraphSchema</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        WidgetGraphSchema,

        /// <summary>Added a specialized content slot to the background blur widget</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        AddedBackgroundBlurContentSlot,

        /// <summary>Updated UserDefinedEnums to have stable keyed display names</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        StableUserDefinedEnumDisplayNames,

        /// <summary>Added "Inline" option to UFontFace assets</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        AddedInlineFontFaceAssets,

        /// <summary>Fix a serialization issue with static mesh FMeshSectionInfoMap FProperty</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        UPropertryForMeshSectionSerialize,

        /// <summary>Adding a version bump for the new fast widget construction in case of problems.</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        FastWidgetTemplates,

        /// <summary>Update material thumbnails to be more intelligent on default primitive shape for certain material types</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        MaterialThumbnailRenderingChanges,

        /// <summary>Introducing a new clipping system for Slate/UMG</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        NewSlateClippingSystem,

        /// <summary>MovieScene Meta Data added as native Serialization</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        MovieSceneMetaDataSerialization,

        /// <summary>Text gathered from properties now adds two variants: a version without the package localization ID (for use at runtime), and a version with it (which is editor-only)</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        GatheredTextEditorOnlyPackageLocId,

        /// <summary>Added AlwaysSign to FNumberFormattingOptions</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        AddedAlwaysSignNumberFormattingOption,

        /// <summary>Added additional objects that must be serialized as part of this new material feature</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        AddedMaterialSharedInputs,

        /// <summary>Added morph target section indices</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        AddedMorphTargetSectionIndices,

        /// <summary>Serialize the instanced static mesh render data, to avoid building it at runtime</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        SerializeInstancedStaticMeshRenderData,

        /// <summary>Change to MeshDescription serialization (moved to release)</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        MeshDescriptionNewSerialization_MovedToRelease,

        /// <summary>New format for mesh description attributes</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        MeshDescriptionNewAttributeFormat,

        /// <summary>Switch root component of SceneCapture actors from MeshComponent to SceneComponent</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        ChangeSceneCaptureRootComponent,

        /// <summary>StaticMesh serializes MeshDescription instead of RawMesh</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        StaticMeshDeprecatedRawMesh,

        /// <summary>MeshDescriptionBulkData contains a Guid used as a DDC key</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        MeshDescriptionBulkDataGuid,

        /// <summary>Change to MeshDescription serialization (removed FMeshPolygon::HoleContours)</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        MeshDescriptionRemovedHoles,

        /// <summary>Change to the WidgetCompoent WindowVisibilty default value</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        ChangedWidgetComponentWindowVisibilityDefault,

        /// <summary>Avoid keying culture invariant display strings during serialization to avoid non-deterministic cooking issues</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        CultureInvariantTextSerializationKeyStability,

        /// <summary>Change to UScrollBar and UScrollBox thickness property (removed implicit padding of 2, so thickness value must be incremented by 4).</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        ScrollBarThicknessChange,

        /// <summary>Deprecated LandscapeHoleMaterial</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        RemoveLandscapeHoleMaterial,

        /// <summary>MeshDescription defined by triangles instead of arbitrary polygons</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        MeshDescriptionTriangles,

        /// <summary>Add weighted area and angle when computing the normals</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        ComputeWeightedNormals,

        /// <summary>SkeletalMesh now can be rebuild in editor, no more need to re-import</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        SkeletalMeshBuildRefactor,

        /// <summary>Move all SkeletalMesh source data into a private uasset in the same package has the skeletalmesh</summary>
        [Introduced(EngineVersion.VER_UE4_25)]
        SkeletalMeshMoveEditorSourceDataToPrivateAsset,

        /// <summary>Parse text only if the number is inside the limits of its type</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        NumberParsingOptionsNumberLimitsAndClamping,

        /// <summary>Make sure we can have more then 255 material in the skeletal mesh source data</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        SkeletalMeshSourceDataSupport16bitOfMaterialNumber,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    };

    /// <summary>
    /// Custom serialization version for changes made in Dev-AnimPhys stream
    /// </summary>
    public enum FAnimPhysObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded,

        /// <summary>convert animnode look at to use just default axis instead of enum, which doesn't do much</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        ConvertAnimNodeLookAtAxis,

        /// <summary>Change FKSphylElem and FKBoxElem to use Rotators not Quats for easier editing</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        BoxSphylElemsUseRotators,

        /// <summary>Change thumbnail scene info and asset import data to be transactional</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        ThumbnailSceneInfoAndAssetImportDataAreTransactional,

        /// <summary>Enabled clothing masks rather than painting parameters directly</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        AddedClothingMaskWorkflow,

        /// <summary>Remove UID from smart name serialize, it just breaks determinism</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        RemoveUIDFromSmartNameSerialize,

        /// <summary>Convert FName Socket to FSocketReference and added TargetReference that support bone and socket</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        CreateTargetReference,

        /// <summary>Tune soft limit stiffness and damping coefficients</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        TuneSoftLimitStiffnessAndDamping,

        /// <summary>Fix possible inf/nans in clothing particle masses</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        FixInvalidClothParticleMasses,

        /// <summary>Moved influence count to cached data</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        CacheClothMeshInfluences,

        /// <summary>Remove GUID from Smart Names entirely + remove automatic name fixup</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        SmartNameRefactorForDeterministicCooking,

        /// <summary>rename the variable and allow individual curves to be set</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        RenameDisableAnimCurvesToAllowAnimCurveEvaluation,

        /// <summary>link curve to LOD, so curve metadata has to include LODIndex</summary>
        [Introduced(EngineVersion.VER_UE4_18)]
        AddLODToCurveMetaData,

        /// <summary>Fixed blend profile references persisting after paste when they aren't compatible</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        FixupBadBlendProfileReferences,

        /// <summary>Allowing multiple audio plugin settings</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        AllowMultipleAudioPluginSettings,

        /// <summary>Change RetargetSource reference to SoftObjectPtr</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        ChangeRetargetSourceReferenceToSoftObjectPtr,

        /// <summary>Save editor only full pose for pose asset</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        SaveEditorOnlyFullPoseForPoseAsset,

        /// <summary>Asset change and cleanup to facilitate new streaming system</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        GeometryCacheAssetDeprecation,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    }

    /// <summary>
    /// Custom serialization version for changes made in Release streams.
    /// </summary>
    public enum FReleaseObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded = 0,

        /// <summary>Static Mesh extended bounds radius fix</summary>
        [Introduced(EngineVersion.VER_UE4_11)]
        StaticMeshExtendedBoundsFix,

        /// <summary>Physics asset bodies are either in the sync scene or the async scene, but not both</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        NoSyncAsyncPhysAsset,

        /// <summary>ULevel was using TTransArray incorrectly (serializing the entire array in addition to individual mutations). converted to a TArray</summary>
        [Introduced(EngineVersion.VER_UE4_13)]
        LevelTransArrayConvertedToTArray,

        /// <summary>Add Component node templates now use their own unique naming scheme to ensure more reliable archetype lookups.</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        AddComponentNodeTemplateUniqueNames,

        /// <summary>Fix a serialization issue with static mesh FMeshSectionInfoMap FProperty</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        UPropertryForMeshSectionSerialize,

        /// <summary>Existing HLOD settings screen size to screen area conversion</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        ConvertHLODScreenSize,

        /// <summary>Adding mesh section info data for existing billboard LOD models</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        SpeedTreeBillboardSectionInfoFixup,

        /// <summary>Change FMovieSceneEventParameters::StructType to be a string asset reference from a TWeakObjectPtr UScriptStruct</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        EventSectionParameterStringAssetRef,

        /// <summary>Remove serialized irradiance map data from skylight.</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        SkyLightRemoveMobileIrradianceMap,

        /// <summary>rename bNoTwist to bAllowTwist</summary>
        [Introduced(EngineVersion.VER_UE4_17)]
        RenameNoTwistToAllowTwistInTwoBoneIK,

        /// <summary>Material layers serialization refactor</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        MaterialLayersParameterSerializationRefactor,

        /// <summary>Added disable flag to skeletal mesh data</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        AddSkeletalMeshSectionDisable,

        /// <summary>Removed objects that were serialized as part of this material feature</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        RemovedMaterialSharedInputCollection,

        /// <summary>HISMC Cluster Tree migration to add new data</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        HISMCClusterTreeMigration,

        /// <summary>Default values on pins in blueprints could be saved incoherently</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        PinDefaultValuesVerified,

        /// <summary>During copy and paste transition getters could end up with broken state machine references</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        FixBrokenStateMachineReferencesInTransitionGetters,

        /// <summary>Change to MeshDescription serialization</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        MeshDescriptionNewSerialization,

        /// <summary>Change to not clamp RGB values > 1 on linear color curves</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        UnclampRGBColorCurves,

        /// <summary>BugFix for FAnimObjectVersion::LinkTimeAnimBlueprintRootDiscovery.</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        LinkTimeAnimBlueprintRootDiscoveryBugFix,

        /// <summary>Change trail anim node variable deprecation</summary>
        [Introduced(EngineVersion.VER_UE4_21)]
        TrailNodeBlendVariableNameChange,

        /// <summary>Make sure the Blueprint Replicated Property Conditions are actually serialized properly.</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        PropertiesSerializeRepCondition,

        /// <summary>DepthOfFieldFocalDistance at 0 now disables DOF instead of DepthOfFieldFstop at 0.</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        FocalDistanceDisablesDOF,

        /// <summary>Removed versioning, but version entry must still exist to keep assets saved with this version loadable</summary>
        [Introduced(EngineVersion.VER_UE4_23)]
        Unused_SoundClass2DReverbSend,

        /// <summary>Groom asset version</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        GroomAssetVersion1,

        /// <summary>Groom asset version</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        GroomAssetVersion2,

        /// <summary>Store applied version of Animation Modifier to use when reverting</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        SerializeAnimModifierState,

        /// <summary>Groom asset version</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        GroomAssetVersion3,

        /// <summary>Upgrade filmback</summary>
        [Introduced(EngineVersion.VER_UE4_24)]
        DeprecateFilmbackSettings,

        /// <summary>custom collision type</summary>
        [Introduced(EngineVersion.VER_UE4_25)]
        CustomImplicitCollisionType,

        /// <summary>FFieldPath will serialize the owner struct reference and only a short path to its property</summary>
        [Introduced(EngineVersion.VER_UE4_25)]
        FFieldPathOwnerSerialization,

        /// <summary>Dummy version to allow us to Fix up the fact that ReleaseObjectVersion was changed elsewhere</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        ReleaseUE4VersionFixup,

        /// <summary>Pin types include a flag that propagates the 'CPF_UObjectWrapper' flag to generated properties</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        PinTypeIncludesUObjectWrapperFlag,

        /// <summary>Added Weight member to FMeshToMeshVertData</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        WeightFMeshToMeshVertData,

        /// <summary>Animation graph node bindings displayed as pins</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        AnimationGraphNodeBindingsDisplayedAsPins,

        /// <summary>Serialized rigvm offset segment paths</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        SerializeRigVMOffsetSegmentPaths,

        /// <summary>Upgrade AbcGeomCacheImportSettings for velocities</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        AbcVelocitiesSupport,

        /// <summary>Add margin support to Chaos Convex</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        MarginAddedToConvexAndBox,

        /// <summary>Add structure data to Chaos Convex</summary>
        [Introduced(EngineVersion.VER_UE4_26)]
        StructureDataAddedToConvex,

        /// <summary>Changed axis UI for LiveLink AxisSwitch Pre Processor</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        AddedFrontRightUpAxesToLiveLinkPreProcessor,

        /// <summary>Some sequencer event sections that were copy-pasted left broken links to the director BP</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        FixupCopiedEventSections,

        /// <summary>Serialize the number of bytes written when serializing function arguments</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        RemoteControlSerializeFunctionArgumentsSize,

        /// <summary>Add loop counters to sequencer's compiled sub-sequence data</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        AddedSubSequenceEntryWarpCounter,

        /// <summary>Remove default resolution limit of 512 pixels for cubemaps generated from long-lat sources</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        LonglatTextureCubeDefaultMaxResolution,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    }

    /// <summary>
    /// Version used for serializing asset registry caches, both runtime and editor
    /// </summary>
    public enum FAssetRegistryVersion
    {
        /// <summary>From before file versioning was implemented</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        PreVersioning = 0,

        /// <summary>The first version of the runtime asset registry to include file versioning.</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        HardSoftDependencies,

        /// <summary>Added FAssetRegistryState and support for piecemeal serialization</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        AddAssetRegistryState,

        /// <summary>AssetData serialization format changed, versions before this are not readable</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        ChangedAssetData,

        /// <summary>Removed MD5 hash from package data</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        RemovedMD5Hash,

        /// <summary>Added hard/soft manage references</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        AddedHardManage,

        /// <summary>Added MD5 hash of cooked package to package data</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        AddedCookedMD5Hash,

        /// <summary>Added UE::AssetRegistry::EDependencyProperty to each dependency</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        AddedDependencyFlags,

        /// <summary>Major tag format change that replaces USE_COMPACT_ASSET_REGISTRY:</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        FixedTags,

        /// <summary>Added Version information to AssetPackageData</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        WorkspaceDomain,

        /// <summary>Added ImportedClasses to AssetPackageData</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        PackageImportedClasses,

        /// <summary>A new version number of UE5 was added to FPackageFileSummary</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        PackageFileSummaryVersionChange,

        /// <summary>Change to linker export/import resource serializationn</summary>
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        ObjectResourceOptionalVersionChange,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    }

    public enum FSequencerObjectVersion
    {
        /// <summary>Before any version changes were made</summary>
        [Introduced(EngineVersion.VER_UE4_OLDEST_LOADABLE_PACKAGE)]
        BeforeCustomVersionWasAdded = 0,

        /// <summary>Per-platform overrides player overrides for media sources changed name and type.</summary>
        [Introduced(EngineVersion.VER_UE4_14)]
        RenameMediaSourcePlatformPlayers,

        /// <summary>Enable root motion isn't the right flag to use, but force root lock</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        ConvertEnableRootMotionToForceRootLock,

        /// <summary>Convert multiple rows to tracks</summary>
        [Introduced(EngineVersion.VER_UE4_15)]
        ConvertMultipleRowsToTracks,

        /// <summary>When finished now defaults to restore state</summary>
        [Introduced(EngineVersion.VER_UE4_16)]
        WhenFinishedDefaultsToRestoreState,

        /// <summary>EvaluationTree added</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        EvaluationTree,

        /// <summary>When finished now defaults to project default</summary>
        [Introduced(EngineVersion.VER_UE4_19)]
        WhenFinishedDefaultsToProjectDefault,

        /// <summary>Use int range rather than float range in FMovieSceneSegment</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        FloatToIntConversion,

        /// <summary>Purged old spawnable blueprint classes from level sequence assets</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        PurgeSpawnableBlueprints,

        /// <summary>Finish UMG evaluation on end</summary>
        [Introduced(EngineVersion.VER_UE4_20)]
        FinishUMGEvaluation,

        /// <summary>Manual serialization of float channel</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        SerializeFloatChannel,

        /// <summary>Change the linear keys so they act the old way and interpolate always.</summary>
        [Introduced(EngineVersion.VER_UE4_22)]
        ModifyLinearKeysForOldInterp,

        /// <summary>Full Manual serialization of float channel</summary>
        [Introduced(EngineVersion.VER_UE4_25)]
        SerializeFloatChannelCompletely,

        /// <summary>Set ContinuouslyRespawn to false by default, added FMovieSceneSpawnable::bNetAddressableName</summary>
        [Introduced(EngineVersion.VER_UE4_27)]
        SpawnableImprovements,

        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION_PLUS_ONE)]
        VersionPlusOne,
        [Introduced(EngineVersion.VER_UE4_AUTOMATIC_VERSION)]
        LatestVersion = VersionPlusOne - 1
    }
}
