using System;
using UAssetAPI.CustomVersions;
using UAssetAPI.PropertyTypes.Objects;

namespace UAssetAPI.UnrealTypes;

public struct FNiagaraVariableCommonReference(AssetBinaryReader reader)
{
    public FName Name = reader.ReadFName();
    public FPackageIndex Type = new FPackageIndex(reader);

    public void Write(AssetBinaryWriter writer)
    {
        writer.Write(Name);
        Type.Write(writer);
    }
}

public class FNiagaraDataInterfaceGeneratedFunction
{
    /** Name of the function as defined by the data interface. */
    public FName DefinitionName;

    /** Name of the instance. Derived from the definition name but made unique for this DI instance and specifier values. */
    public FString InstanceName;

    /** Specifier values for this instance. */
    public (FName, FName)[] Specifiers;

    public FNiagaraVariableCommonReference[] VariadicInputs = [];
    public FNiagaraVariableCommonReference[] VariadicOutputs = [];
    public ushort MiscUsageBitMask;

    public FNiagaraDataInterfaceGeneratedFunction() { }

    public FNiagaraDataInterfaceGeneratedFunction(AssetBinaryReader reader)
    {
        DefinitionName = reader.ReadFName();
        InstanceName = reader.ReadFString();

        Specifiers = reader.ReadArray(() => (reader.ReadFName(), reader.ReadFName()));

        if (reader.Asset.GetCustomVersion<FNiagaraCustomVersion>() >= FNiagaraCustomVersion.AddVariadicParametersToGPUFunctionInfo)
        {
            VariadicInputs = reader.ReadArray(() => new FNiagaraVariableCommonReference(reader));
            VariadicOutputs = reader.ReadArray(() => new FNiagaraVariableCommonReference(reader));
        }

        if (reader.Asset.GetCustomVersion<FNiagaraCustomVersion>() >= FNiagaraCustomVersion.SerializeUsageBitMaskToGPUFunctionInfo)
            MiscUsageBitMask = reader.ReadUInt16();
    }

    public void Write(AssetBinaryWriter writer)
    {
        writer.Write(DefinitionName);
        writer.Write(InstanceName);

        writer.Write(Specifiers.Length);
        foreach (var spec in Specifiers)
        {
            writer.Write(spec.Item1);
            writer.Write(spec.Item2);
        }

        if (writer.Asset.GetCustomVersion<FNiagaraCustomVersion>() >= FNiagaraCustomVersion.AddVariadicParametersToGPUFunctionInfo)
        {
            writer.Write(VariadicInputs.Length);
            foreach (var input in VariadicInputs)
            {
                input.Write(writer);
            }

            writer.Write(VariadicOutputs.Length);
            foreach (var output in VariadicOutputs)
            {
                output.Write(writer);
            }
        }

        if (writer.Asset.GetCustomVersion<FNiagaraCustomVersion>() >= FNiagaraCustomVersion.SerializeUsageBitMaskToGPUFunctionInfo)
            writer.Write(MiscUsageBitMask);
    }
}

public class FNiagaraDataInterfaceGPUParamInfo : IStruct<FNiagaraDataInterfaceGPUParamInfo>
{
    /** Symbol of this DI in the hlsl. Used for binding parameters. */
    public FString DataInterfaceHLSLSymbol;

    /** Name of the class for this data interface. Used for constructing the correct parameters struct. */
    public FString DIClassName;

    /** Information about all the functions generated by the translator for this data interface. */
    public FNiagaraDataInterfaceGeneratedFunction[] GeneratedFunctions = [];

    public FNiagaraDataInterfaceGPUParamInfo() { }

    public FNiagaraDataInterfaceGPUParamInfo(AssetBinaryReader reader)
    {
        DataInterfaceHLSLSymbol = reader.ReadFString();
        DIClassName = reader.ReadFString();

        if (reader.Asset.GetCustomVersion<FNiagaraCustomVersion>() >= FNiagaraCustomVersion.AddGeneratedFunctionsToGPUParamInfo)
        {
            GeneratedFunctions = reader.ReadArray(() => new FNiagaraDataInterfaceGeneratedFunction(reader));
        }
    }

    public static FNiagaraDataInterfaceGPUParamInfo Read(AssetBinaryReader reader) => new FNiagaraDataInterfaceGPUParamInfo(reader);

    public int Write(AssetBinaryWriter writer)
    {
        var offset = writer.BaseStream.Position;
        writer.Write(DataInterfaceHLSLSymbol);
        writer.Write(DIClassName);
        if (writer.Asset.GetCustomVersion<FNiagaraCustomVersion>() >= FNiagaraCustomVersion.AddGeneratedFunctionsToGPUParamInfo)
        {
            writer.Write(GeneratedFunctions.Length);
            foreach (var func in GeneratedFunctions)
            {
                func.Write(writer);
            }
        }

        return (int)(writer.BaseStream.Position - offset);
    }

    public static FNiagaraDataInterfaceGPUParamInfo FromString(string[] d, UAsset asset)
    {
        throw new NotImplementedException();
    }
}
